import { Flex, Spinner } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Register App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100vh" bg="secondary" padding={4}>
        <Spinner color="primary" size="lg" marginX="auto"/>
      </Flex>
    </div>
  )
}

export default Home
