import { Flex, Spinner } from "@chakra-ui/react";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";

const Home: NextPage = () => {
  const router = useRouter();
  useEffect(() => {
    setTimeout(() => {
      router.replace({ pathname: "/admin/register" });
    }, 1000);
  }, []);

  return (
    <div>
      <Head>
        <title>Register App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex alignItems="center" h="100vh" bg="secondary" padding={4}>
        <Spinner color="primary" size="lg" marginX="auto" />
      </Flex>
    </div>
  );
};

export default Home;
